site_name: My Creality K1 Guide
theme:
  name: material
  features:
    - navigation.expand
  icon:
    logo: material/printer-3d
    repo: fontawesome/brands/github
  language: en

extra_css:
  - stylesheets/youtube.css

# add repo to mkdocs
repo_name: meteyou/creality-k1
repo_url: https://github.com/meteyou/creality-k1

# navigation
nav:
  - Introduction: index.md
  - Hardware:
      - Index: hardware/index.md
      - Filament path: hardware/filament-path.md
      - Extruder grip: hardware/extruder-grip.md
      - Door rattling: hardware/door-rattling.md
  - Software:
      - Index: software/index.md
      - Root access: software/root-access.md
      - Moonraker: software/moonraker.md
      - Mainsail: software/mainsail.md
      - Klipper: software/klipper.md
  - Links: links.md

# markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html

# add some social media buttons to the footer
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/meteyou
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@meteyou
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/meteyou
